#!/usr/bin/env bash

uname=`uname -s`

lecho() {
    >&2 echo $1
}

lecho "C compiler is: ${CC:=cc}"

get_inc_list() {
    ${CC:-cc} $CFLAGS -x$1 -E -v /dev/null 2>&1 1>/dev/null | tac |\
        awk '/\#include <...> search starts here:/{p=0;exit}p;/\End of search list/{p=1}'\
        | sed 's/^[ \t]*//'
}

comm <(get_inc_list c++ | sort) <(get_inc_list c | sort) -3 |\
    tr '\n' ':' | sed 's/^/COMPILEOPTS += -I/;s/:$//;s/:/ -I/g;s/$/\n/'

if [ -n "$LIBSTD" ]; then
    lecho "Using explicitly given C++ standard library: lib$LIBSTD"
elif [ $uname == Darwin ]; then
    lecho "Detected Darwin; using libc++"
    LIBSTD=c++
elif [ $uname == FreeBSD ]; then
    lecho "Detected FreeBSD; using libc++"
    LIBSTD=c++
elif [ $uname == Linux ]; then
    lecho "Detected Linux; using libstdc++"
    LIBSTD=stdc++
else
    lecho "Unknown OS; using libstdc++"
    LIBSTD=stdc++
fi

echo "LINKOPTS += -l$LIBSTD"

echo "LANGUAGES += c"
echo "COMPILER = $CC"
